### ISSUE TITLE
Create your first milestone.

### ISSUE THREAD

**Issue by brucellino** [sci-gaia/LagosHackfest#47]
Hi 

During your presentation you gave us an implementation strategy. We would like you to create a milestone for the mid-hackfest status.

Follow this checklist to create the milestone (check off the items as you go)

  1. [ ] Go to your repository, and select the "issues" tab. 
  1. [ ] On the issues tab, there are two buttons for "issues" and "milestones"  - click on "milestones" 
  1. [ ] You should see a green button called "create new milestone". Click on that to create a new milestone
    1. [ ] As the title of the milestone, use "Lagos-Hackfest Halfway Mark"
    1. [ ] Fill out the description of the Milestone -use the implementation strategy that you had in your slides.
    1. [ ] Set the deadline for 25 November 2016
  1. [ ] Plan your project 
    1. [ ] Define tasks which need to be done in order to reach your implementation goal. Choose as many as you like, but make sure that they are _realistic_ and can be done in a few days. These can also include things like "clarify how to use FutureGateway", etc.

**Comment by brucellino** [comment]
hi @icuzochukwu  , can you let  us know if you've written the milestone objectives ? you should have a list of issues in the milestone which define tasks in achieving your goals.

**Comment by icuzochukwu** [comment]
Our issues and milestone are listed on our repository (https://github.com/unizik/D4PR).

**Comment by mtorrisi** [comment]
Ok, thanks
